### ISSUE TITLE
Why this package and rollup question

### ISSUE THREAD

**Issue by frederikhors** [lunchboxer/graphql-subscriptions-client#1]
Can you better explain why this package?

I'm having problem with original Apollo `subscriptions-transport-ws` and rollup (https://github.com/apollographql/subscriptions-transport-ws/issues/563).

Can I use this one instead?

Is this just client side code?

Thanks.

**Comment by lunchboxer** [comment]
That is basically the purpose of this package. I had problems using rollup so I made this package to use instead. I have only used it on the client side

**Comment by frederikhors** [comment]
How did you fixed the rollup integration?

**Comment by lunchboxer** [comment]
Nothing magical really. You can see if you compare the source, that it's actually not very different. I've just removed some things. I was having problems where when rollup it couldn't find the export and with declaring a websocket implementation. I am not super clear on this. Since I don't remember well. I have been using this client for a while since it does what subscription-transport-ws does, but without the rollup problems. If you are using SSR then you will want subscription-transport-ws or fork this version and reimplement declaring a custom websocket implementation. Using this on with SSR would result in an error that WebSocket isn't defined.

I didn't know anyone else would be using this, so I didn't document it properly, but I'll try to go back and add the details you are requesting.
