### ISSUE TITLE
What about enisdenjo/graphql-ws ?

### ISSUE THREAD

**Issue by Toub** [lunchboxer/graphql-subscriptions-client#13]
Original package https://github.com/apollographql/subscriptions-transport-ws suggests to use https://github.com/enisdenjo/graphql-ws instead.

It looks to have good support and is bundled with rollup.

Would you also recommend to use it instead of this one?

In anycase, what about adding a note with your opinion in your readme?

**Comment by lunchboxer** [comment]
Looks great and seems to have pretty good docs, too. I'll have to check it out. Before I actually use it I can only make a few simple comments. That library is intended to work as client and server. Many may find that to be convenient, but I didn't need it. It looks like a much better implementation of an API that looks very similar at first glance. I'm guessing it's way better supported. I'm not developing any new realtime graphql web apps at the moment, but I'll have to give that one a try. This library works fine, but for new projects I'd guess that one is a better bet, since docs seem like they might be better. If bundle size matters, I think there is probably a small advantage in this library, but I'm only guessing.

**Comment by lunchboxer** [comment]
I have adjusted the README to reflect the existance of graphql-ws. Thanks for bringing this to my attention.
